### ISSUE TITLE
Install 도 안되고 vs 2015에서 열리지 않습니다.

### ISSUE THREAD

**Issue by pawhang** [OpenBapul/iamport-rest-client-net#43]
#####   패키지 에러나는데요?? 어떻게 해야 할지..

종속성 'Newtonsoft.Json (≥ 10.0.2)'을(를) 확인 중입니다.
Install-Package : 'Newtonsoft.Json'에 이미 'Microsoft.CSharp'에 대한 종속성이 정의되어 있습니다.
위치 줄:1 문자:1
+ Install-Package Iamport.RestApi
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

#####  솔루션을 직접 열러고 하는데도 에러 납니다.

솔루션의 프로젝트 중 하나 이상이 제대로 로드되지 않습니다.
C:\Users\Administrator\Downloads\임시\iamport-rest-client-net-master\src\Iamport.RestApi\Iamport.RestApi.csproj : error  : 프로젝트의 기본 XML 네임스페이스는 MSBuild XML 네임스페이스여야 합니다. 프로젝트를 MSBuild 2003 형식으로 작성한 경우에는 <Project> 요소에 xmlns="http://schemas.microsoft.com/developer/msbuild/2003"을(를) 추가하고, 프로젝트를 이전 1.0 또는 1.2 형식으로 작성한 경우에는 MSBuild 2003 형식으로 변환하십시오.  C:\Users\Administrator\Downloads\임시\iamport-rest-client-net-master\src\Iamport.RestApi\Iamport.RestApi.csproj

C:\Users\Administrator\Downloads\임시\iamport-rest-client-net-master\test\Iamport.RestApi.Tests\Iamport.RestApi.Tests.csproj : error  : 프로젝트의 기본 XML 네임스페이스는 MSBuild XML 네임스페이스여야 합니다. 프로젝트를 MSBuild 2003 형식으로 작성한 경우에는 <Project> 요소에 xmlns="http://schemas.microsoft.com/developer/msbuild/2003"을(를) 추가하고, 프로젝트를 이전 1.0 또는 1.2 형식으로 작성한 경우에는 MSBuild 2003 형식으로 변환하십시오.  C:\Users\Administrator\Downloads\임시\iamport-rest-client-net-master\test\Iamport.RestApi.Tests\Iamport.RestApi.Tests.csproj

C:\Users\Administrator\Downloads\임시\iamport-rest-client-net-master\Samples\Sample.AspNetCore\Sample.AspNetCore.csproj : error  : 프로젝트의 기본 XML 네임스페이스는 MSBuild XML 네임스페이스여야 합니다. 프로젝트를 MSBuild 2003 형식으로 작성한 경우에는 <Project> 요소에 xmlns="http://schemas.microsoft.com/developer/msbuild/2003"을(를) 추가하고, 프로젝트를 이전 1.0 또는 1.2 형식으로 작성한 경우에는 MSBuild 2003 형식으로 변환하십시오.  C:\Users\Administrator\Downloads\임시\iamport-rest-client-net-master\Samples\Sample.AspNetCore\Sample.AspNetCore.csproj

**Comment by gongdo** [comment]
아차, readme 업데이트가 늦었습니다. 현재 개발은 VS2017로 하고 있는데요, 누겟에서 받은것도 안된다는거죠? 현재 프로젝트의 닷넷 프레임워크 버전이 어떻게 될까요?
최소 지원 버전은 .NET 4.5 이상입니다.

**Comment by pawhang** [comment]
Nuget 설치가 에러 때문에 안됩니다. 에러는 이건데요..
Install-Package : 'Newtonsoft.Json'에 이미 'Microsoft.CSharp'에 대한 종속성이 정의되어 있습니다.

기존 쓰던 Newtonsoft.Json와 버전이 안 맞는 건지??

**Comment by gongdo** [comment]
@pawhang 다시 한번, 개발 환경이 어떻게 되시나요?
- Visual Studio 버전
- 타겟 프로젝트의 .NET Framework 버전

**Comment by pawhang** [comment]
Visual Studio 2015
Visual Studio 2017 은 파이썬만...
닷넷프레임웍 4.52
widdows 2012 r2

**Comment by pawhang** [comment]
문제가 안 풀리면..
혹 라이브러리만이라도 받아서 해 보고 싶은데요.. 받을 수 있나요?

**Comment by gongdo** [comment]
@pawhang NuGet자체가 라이브러리입니다.
일단 VS2015 환경을 구할 수 있다면 테스트해보도록 하지요.
VS2017에서는 .NET Framework 4.5 부터 4.6.2까지 모두 문제 없는걸 확인했는데, 환경적인 차이가 왜 나는지 모르겠습니다.
가능하다면 문제를 재현 할 수 있는 방법을 알려주시면 찾는데 도움이 되겠습니다.

**Comment by pawhang** [comment]
NuGet 다운로드 가 안되요.. 에러때문에

**Comment by gongdo** [comment]
@pawhang https://www.nuget.org/packages/Iamport.RestApi/ 여기에서 Download를 하시면 됩니다. NuGet이니까요.

**Comment by pawhang** [comment]
에러 내용 함 바주시면 감사드립니다.
www.gudoc.com/iamport.png

**Comment by gongdo** [comment]
@pawhang 오류 내용은 이해합니다만, 환경이 정확히 어떤지 알 수가 없습니다. 재현이 불가능하면 수정도 불가능합니다. 오히려 저를 도와주셔야 제가 수정할 수 있습니다. 계속 말씀드리지만 정확한 환경 정보가 없으면 제가 재현을 해볼 수가 없습니다.
구체적인 비주얼 스튜디오 버전, 닷넷 프레임워크 버전이라도 알 수 있으면 비슷하게나마 재현을 해볼 수 있겠습니다.

**Comment by gongdo** [comment]
@pawhang https://github.com/JamesNK/Newtonsoft.Json/issues/1265 이 문제가 아닐까 싶네요. 
https://dist.nuget.org/index.html 여기에서 환경에 맞는 최신 NuGet 확장을 다운로드 받아보세요.

**Comment by gongdo** [comment]
@pawhang 올려주신 스크린샷은 민감한 정보가 포함되어 있을 수도 있어서 삭제했습니다. 양해바랍니다.

**Comment by pawhang** [comment]
제가 2017, 2015, 2013 다 쓰다보니.. 헷깔렸습니다.
VS 2013으로 웹을 열어놓구, 2015로 폼개발하고, 2017로 파이썬 공부하고.. 이러다 보니..
VS 2013에서 NuGet 버전 문제가 있었네요.
NeGet 버전 문제 해결하려고 하니. 아래 삭제하라고 하네요.
Tool for Apache Cordova for Visual Studio 2013 - CTP3  삭제하는데 시간이 1시간 걸림

그리고 문제를 해결했습니다.
VS 2015로 프로젝트 다시 열고 (웹이라서 어렵지 않았음)
그리고 NuGet 버전은 업데이트 되어 있으니.
Microsoft.AspNet.Razor.ko 3.2.2 업데이트하고
Newtonsoft.json 버전도 업데이트
아임포트 인스톨하니 잘 설치 되었습니다.  Install-Package Iamport.RestApi

답변 감사드리고 꾸벅꾸뻑
그리고 링크 삭제 감사합니다.

**Comment by gongdo** [comment]
해결되어 다행입니다. 아무쪼록 다른 문제가 없길 바랍니다. :)
